name: Deploy Canvas Lite

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests (optional, if you add any)
      #- name: Run tests
      #  run: npm test

      # 5. Run the app (for example on a server or preview)
      #    You might want to use PM2 or a container for production
      - name: Start app
        run: |
          echo "Starting Canvas Lite..."
          node server.js &

      # 6. Optional: deploy to a cloud service
      #    e.g., Render, Heroku, Vercel, etc.  
      #    You would add deployment steps here
